solvcon/devenv

.github/workflows/solvcon_install.yml
README.md
devenv-cli.sh
prepare-solvcon-dev.sh

This pull request provides the build process to build SOLVCON in the same way as its CI. The script is tested in Ubuntu 18.04 and I expect it should also work on macOS because it is mainly based on anaconda.
I hope this pull request is the first step for us to build the whole stack including the 3rd-party libraries, or initiate our implementation strategy at least. Please feel free to comment , decline, or offer the other and better step below. I am also open to convert this pull request to be "draft" and keep it as a discussion thread.

feat(entry-point): the very first script to invoke

---

README.md

Add project scope in the README file.  We can use this PR to discuss what is missing or unclear.
Also see the [previous discussion](https://github.com/solvcon/seminar/discussions/10).

Update README to include the project scope

---

bin/devenv
scripts/cmd.d/add
scripts/cmd.d/build
scripts/cmd.d/del
scripts/env.d/devenv_impl
scripts/env.d/vars
scripts/func.d/bash_utils
scripts/func.d/build_utils
scripts/init

As title, me and @chestercheng refined devenv and it should work properly.
And @chestercheng seems not a member of this group, should we invite him?

feat: all-in devenv

---

scripts/build.d/bzip2
scripts/build.d/cmake
scripts/build.d/openssl
scripts/build.d/python
scripts/build.d/xz
scripts/build.d/zlib

As title, I added bzip2, xz, cmake, openssl, python, zlib build scripts.

feat: add some build scripts

---

.gitignore
README.md
scripts/build.d/gmsh

1. `source scripts/init`
2. `devnev add solvcon-01`
3. `devenv use solvcon-01`
4. `devenv build cmake`
`devenv build gmsh`
```
-- Installing: /home/tai271828/work-my-projects/solvcon/devenv/flavors/solvcon-01/usr/share/doc/gmsh/demos/simple_geo/sphere.geo
-- Installing: /home/tai271828/work-my-projects/solvcon/devenv/flavors/solvcon-01/usr/share/doc/gmsh/demos/simple_geo/splines.geo
-- Installing: /home/tai271828/work-my-projects/solvcon/devenv/flavors/solvcon-01/usr/share/doc/gmsh/demos/simple_geo/square_regular.geo
-- Installing: /home/tai271828/work-my-projects/solvcon/devenv/flavors/solvcon-01/usr/share/doc/gmsh/demos/simple_geo/tower.geo
-- Installing: /home/tai271828/work-my-projects/solvcon/devenv/flavors/solvcon-01/usr/share/doc/gmsh/demos/simple_geo/tower.i1
-- Installing: …
```

Add build script for gmsh

---

scripts/build.d/cython
scripts/build.d/hdf
scripts/build.d/modmesh
scripts/build.d/netcdf
scripts/build.d/numpy
scripts/build.d/openblas
scripts/build.d/pybind11

Added following build scripts:
1.  cython
2. hdf
3. modmesh
4. netcdf
5. numpy
6. openblas
7. pybind11

feat: added more scripts

---

scripts/build.d/scotch

Added scotch build script, this script compatible with `OSX` and `x86 Linux`.

feat: add scotch build scripts

---

.gitignore
scripts/build.d/scotch
scripts/env.d/vars
scripts/func.d/build_utils

#32 
Md5 check sum is old but that's what I had used before.  Later it may be upgraded to newer checksum.

Implement build from downloaded tarball (with md5 check sum)

---

scripts/cmd.d/show

Add a shortcut command to print `DEVENVFLAVOR`.

Add a new command named show to print the current environment / flavor

---

tests/runner.sh
tests/test_bash_utils.sh

test(tests): create test_bash_utils.sh

---

tests/test_bash_utils.sh

feat(tests): add get_list unit tests

---

scripts/env.d/devenv_impl
scripts/init
tests/runner.sh
tests/test_devenv_impl.sh

@j8xixo12 @chestercheng I added a function for the main logic in `devenv_impl` to individually test `namemunge` and `nameremove` functions.
Issues #48 #49

Add unit tests for namemunge and nameremove in devenv_impl

---

scripts/build.d/cython
scripts/build.d/numpy
scripts/build.d/openblas
scripts/build.d/openssl
scripts/build.d/python
scripts/func.d/build_utils

* In build_util, enhance syncgit() function to take an optional 4th argument for the directory name of the git repository
* Use the fixed version 1.1.1b for openssl
* Use the fixed version 0.3.17 for openblas
* Use the fixed version 0.29.24 for Cython

Update the build scripts up to numpy

---

.github/workflows/shunit2_runner.yml
tests/runner.sh
tests/test_init_var.sh

This is to address issue #53 .

Run macos-10.15 unit test on Github action

---

scripts/cmd.d/list

bug_fix: fixed list return value

---

scripts/build.d/make
scripts/build.d/netcdf

Add a build script for GNU make, and augment the build script of netcdf to allow building from tarball.

Change to build script (netcdf and gnu make)

---

scripts/build.d/sqlite

1. `source scripts/init`
2. `devnev add prime`
3. `devenv use prime`
`devenv build sqlite`
Build pass and get sqlite lib ready to use

Add build script for sqlite

---

applications/solvcon/conda.sh
applications/solvcon/entry.sh

SOLVCON has done some house cleaning when integrating devenv. This pull request aligns the effort of house cleaning.
1. `devenv add demo`
2. `devenv use demo`
3. `devenv launch solvcon`
Pre-requisite code merge https://github.com/solvcon/solvcon/pull/244

Align solvcon build parity

---

.github/workflows/shunit2_runner.yml
.github/workflows/solvcon_runner.yml

Similar to what SOLVCON itself has done, let's enable a similar check for the build of the whole stack https://github.com/solvcon/solvcon/pull/248

Enable weekly SOLVCON build schedule

---

scripts/build.d/bzip2

Added macOS's sed into bzip2 build script to fix build failed issue

fix: fixed macos build failed

---

applications/solvcon/entry.sh
scripts/application.d/solvcon

Along with the pull request https://github.com/solvcon/solvcon/pull/253 , this pull request will revive our CI by fixing issue #98 .

Fix issues #98 the recent CI fails

---

.github/workflows/build_pkg_runner.yml
.github/workflows/solvcon_runner.yml

Issue: #100 Bump CI from Ubuntu 18.04 to 20.04 for application SOLVCON
See the testing CI job run with my personal Action https://github.com/tai271828/devenv/runs/4999080845?check_suite_focus=true

Resolve issue #100

---

scripts/build.d/pyside6

Add a build script for just pyside for qt, but not qt itself.

Add build script for pyside6

---

scripts/build.d/qt

I found the file format in the zip file is **dos**, obviously zip is for Windows
tar.xz is for unix, therefore I change the file type from zip to tar.xz

change qt tarball file type to tat.xz

---

scripts/build.d/ag

Add silver searcher build script

---

scripts/build.d/git

Add build script for git (version 2.39.0)

---

scripts/build.d/cython
scripts/build.d/numpy

* Update numpy version to 1.24.1 and fix it using tarball
* Update Cython version to 0.29.32 and fix it using tarball
This fixes #117, tested with RHEL 7.3.  I am not sure about git main branch though.

Update numpy build script

---

scripts/build.d/numpy

fix(numpy): update git submodules to resolve build failed

---

bin/devenv
scripts/build.d/ag
scripts/build.d/cmake
scripts/build.d/cython
scripts/build.d/git
scripts/build.d/libevent
scripts/build.d/modmesh
scripts/build.d/numpy
scripts/build.d/openssl
scripts/build.d/pybind11
scripts/build.d/pyside6
scripts/build.d/python
scripts/build.d/tmux
scripts/cmd.d/add
scripts/cmd.d/build
scripts/cmd.d/del
scripts/cmd.d/launch
scripts/cmd.d/list
scripts/cmd.d/show
scripts/func.d/bash_utils
scripts/init
tests/test_bash_utils.sh

Change the function name 'display()' to 'devenv_display()' due to the conflict between devenv and the package 'imagemagick'

Change the function name 'display()' to 'devenv_display()' 

---

scripts/build.d/vim

I added a build script for vim with basic functionality.
Since there is no release in tarball format with its md5sum for vim, I only added the "git" source.
Please take a look at my PR. Thanks.
This resolves #124.

Add build script for vim

---

scripts/build.d/vim

fix: should let tar to determine which mode to apply in vim build script

---

scripts/build.d/pybind11

I coincidentally found the tarball url is wrong in this script, so I fixed it.

fix: tarball url is wrong in pybind11 build script

---

scripts/build.d/zlib

I added zlib build script tarball download support

feat: add tarball download for zlib

---

scripts/build.d/python
scripts/build.d/sqlite
scripts/func.d/build_utils

Also:
* Update sqlite build script to use SRCSYNC environment variable.
* Include timing information in the `buildcmd` function.

Update Python building script

---

scripts/build.d/pyside6

Try to find llvm and qtpaths from the environment

Update pyside6: detect LLVM_INSTALL_DIR/QTPATHS
