build-pybind11-in-conda.sh, conda.sh, devenv-cli.sh, prepare-solvcon-dev.sh
By copying the files used to build devenv from SOLVCON repository, we
could build devenv without depending on SOLVCON.
Issue #6
=> Decouple SOLVCON repository for devenv building

bin/devenv
``devenv`` crashes when ``$DEVENVROOT`` is not set before running the command.
=> Err out when DEVENVROOT is not set

scripts/func.d/bash_utils, scripts/init
As title, I added devenv command autocomplete, 
devenv can autocomplete it own command, `add` , `build`, `del`, `off`, `use`
and the following command also have autocomplete:
`use`, `del` will show the folders contained by `flavor`
`build` will show build scripts contain by `build.d`, if `build.d` not exist will show nothing
=> feat: add devenv command autocomplete

applications/solvcon/conda.sh, applications/solvcon/prepare-solvcon-dev.sh, bin/build-application-solvcon-devenv.sh
We have introduced gmsh as one of our build component in this commit https://github.com/solvcon/devenv/pull/19 . This pull request is a follow-up task to integrate the usage of gmsh build component of `devenv` and SOLVCON.
1. `source scripts/init`
2. `devnev add solvcon-01`
3. `devenv use solvcon-01`
4. `bin/build-application-solvcon-devenv.sh`
SOLVCON could pass its unittest with the environment built by devenv.
=> Integrate SOLVCON and gmsh build

README.md, scripts/build.d/bzip2, scripts/build.d/cmake, scripts/build.d/cython, scripts/build.d/gmsh, scripts/build.d/hdf, scripts/build.d/modmesh, scripts/build.d/netcdf, scripts/build.d/numpy, scripts/build.d/openblas, scripts/build.d/openssl, scripts/build.d/pybind11, scripts/build.d/python, scripts/build.d/scotch, scripts/build.d/xz, scripts/build.d/zlib, scripts/cmd.d/add, scripts/cmd.d/del, scripts/env.d/devenv_impl, scripts/env.d/vars, scripts/func.d/bash_utils, scripts/func.d/build_utils, scripts/init
* Related issue: #31
* Description:
With this PR you may define the `DEVENVFLAVORROOT` environment variable to point to the flavors path where you want.
* Example:
```bash
┌── .devenv [feat/customized-flavors-dir]
└─❯ export DEVENVFLAVORROOT=$HOME/.flavors
┌── .devenv [feat/customized-flavors-dir]
└─❯ source scripts/init
┌── .devenv [feat/customized-flavors-dir]
└─❯ devenv use issue31 
now using 'issue31'
┌── .devenv [feat/customized-flavors-dir] (issue31)
└─❯ env | grep ^DEVENV
DEVENVFLAVOR=issue31
DEVENVFLAVORROOT=/home/chestercheng/.flavors
DEVENVPATH_BACKUP=/home/chestercheng/.local/bin:/home/chestercheng/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
DEVENVPREFIX=/home/chestercheng/.flavors/issue31/usr …
```
=> add DEVENVFLAVORROOT to support customized flavor dir

applications/solvcon/prepare-solvcon-dev.sh, bin/devenv, scripts/application.d/solvcon, scripts/cmd.d/launch, scripts/func.d/bash_utils, scripts/init
In the [sciwork online sprint today](https://hackmd.io/UbOReM5CQcmtP5gL1zxqqw?view), this is the feature we have implemented for issue: #26 .
1. `source scripts/init`
1. `devenv use flavor-issue-26`
1. `devenv launch solvcon`
1. SOLVCON will be built
2. `flavor/flavor-issue-26/application-solvcon` is created
This pull request only closes https://github.com/solvcon/devenv/issues/26 but not fully completes https://github.com/solvcon/devenv/discussions/23 for the follow incomplete tasks and imperfect features:
1. Uses still need to manually re-launch SOLVCON
2. SOLVCON source and lib are not fully integrated with `flavor/usr/`, `flavor/usr/bin`, and `flavor/src`.
I will create follow-up pull requests to complete above tasks later on to prevent a single huge pull request for code review. …
=> feat(launch): init support of launching applications

.github/workflows/solvcon_install.yml, .gitignore, .gitmodules, README.md, tests/runner.sh, tests/test_init_var.sh
issue: #3
Trying to use `shunit2` to build faster and more comprehensive unittest for CI. Please note currently macOS runtime testing is skipped. I don't have macOS and it's inefficient for me to develop cases for macOS. It's welcome to add up more jobs for macOS. Thanks!
Please follow the updated README in this pull request to figure out how to trigger the unittest and verify this pull request.
=> test(tests): init unittest with shunit2

scripts/build.d/bzip2
When I tried to import `pandas` which will use bzip2 via shared library, but it can not find `libbz2.so`, so that I found the `bzip2` makefile only build the static library, it didn't build shared library.
If you want to build shared library, you need to call **another makefile**, and this makefile didn't help you to i**nstall shared library**, you need to install it **manually**, therefore I enhanced `bzip2` script.
here is the reference [link](http://www.iitk.ac.in/LDP/LDP/lfs/5.0/html/chapter06/bzip2.html)
=> feat: bzip2 script enhance

README.md
This PR only fixes the typesetting of README.
=> Format the README style

bin/devenv, scripts/init
Typing `devenv` alone showed only the help message but not the active environment.  With this PR, `devenv` alone shows the active environment:
```
$ devenv
'mainde' is active: /Users/yungyuc/.devenv/flavors/mainde
```
If there is not an active environment:
```
$ devenv
```
=> Make devenv function to print the active environment

scripts/build.d/pybind11
Keep pybind11 build to use git by default, but add an option to use tarball.
=> Improve pybind11 build script

scripts/build.d/python
There are some little different when install `pip` between `python 2.7` and `python 3`,
this commit allow python build script at `pip` installing can compatible with `python2.7` and `python 3`.
=> feat: enhance pip install sequence

bin/build-application-solvcon-devenv.sh
issue: #66
1. `devenv add flavor1`
2. `devenv use flavor1`
3. `devenv launch solvcon`
The application `solvcon` is built and passes a quick self-test. `devenv show` only shows `flavor1` without the other flavor `solvcon-devenv`.
=> fix(applications): sync up runtime flavors

scripts/init
`scripts/init` reads a new variable `DEVENVALIAS` that creates an alias to `devenv` and enables autocomplete for the alias.  To use the new feature provided in the patch, in `.bashrc`, add:
```bash
if [ -f ~/devenv/scripts/init ]; then
DEVENVALIAS=sd
source ~/devenv/scripts/init
fi
```
It enables:
```console
$ sd<tab>
add     build   del     launch  list    off     show    use
```
and 
```console
$ sd
Usage: devenv [command]
Description:
Tool to manage development environment in console
...
```
=> Add "DEVENVALIAS" variable to create an alias to "devenv" driver command

bin/devenv
The usage of show is shown.
```
jenny@moria:~/devenv/bin$ devenv
Usage: devenv [command]
Description:
Tool to manage development environment in console
Variables:
DEVENVROOT=/home/jenny/devenv
DEVENVDLROOT=/home/jenny/devenv/var/downloaded
DEVENVFLAVOR=
Commands:
list   - list all available environments
use    - activate an environment
off    - deactivate the environment
add    - create a new environment directory
del    - delete a existing environment directory
build  - build a package in the active environment
launch - launch an application
show   - print the current environment/flavor
```
=> Add usage of show

README.md
The usage of show is shown in README.md 
```
$ devenv
Usage: devenv [command]
Description:
Tool to manage development environment in console
Variables:
DEVENVROOT=/path/to
DEVENVDLROOT=/path/to/var/downloaded
DEVENVFLAVOR=
Commands:
list   - list all available environments
use    - activate an environment
off    - deactivate the environment
add    - create a new environment directory
del    - delete a existing environment directory
build  - build a package in the active environment
launch - launch an application
show   - print the current environment
```
=> Add usage of show in README.md

scripts/build.d/numpy
With the `--old-and-unmanageable` switch, the numpy will be installed in a directory without version number, like site-`package/numpy/`.  It makes it easier to hard code inclusion path in configuration file.
=> [build/numpy] Add --old-and-unmanageable

.gitignore, scripts/env.d/vars, scripts/init, tests/test_bash_utils.sh, tests/test_devenv_impl.sh, tests/test_init_var.sh
Before using a flavor:
```console
$ devenv
Usage: devenv [command]
Description:
Tool to manage development environment in console
Variables:
DEVENVROOT=/Users/yungyuc/work/devenv
DEVENVDLROOT=/Users/yungyuc/work/devenv/var/downloaded
DEVENVFLAVOR=
DEVENVFLAVORROOT=/Users/yungyuc/work/devenv/flavors
DEVENVCURRENTROOT=/dev/null
```
After using a flavor:
```console
$ devenv use prime ; devenv
now using 'prime'
'prime' is active: /Users/yungyuc/work/devenv/flavors/prime
Usage: devenv [command]
Description:
Tool to manage development environment in console
Variables:
DEVENVROOT=/Users/yungyuc/work/devenv
DEVENVDLROOT=/Users/yungyuc/work/devenv/var/downloaded
DEVENVFLAVOR=prime
DEVENVFLAVORROOT=/Users/yungyuc/work/devenv/flavors …
```
=> Set DEVENVCURRENTROOT back to /dev/null after devenv off

scripts/build.d/python
Run into errors when building python with `devenv build python`:
```
<skipped>                                                                                                                            
Could not build the ssl module!
Python requires a OpenSSL 1.1.1 or newer
<skipped>
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not …
```
=> feat(build): python: provide more hints for prerequisite

scripts/build.d/bzip2
The root cause of https://github.com/solvcon/devenv/issues/92 is bzip2 using `-soname` as `LDFLAGS` in makefile, but MacOS default C compiler is clang and the `LDFLAGS` is `-install_name`, so devenv failed to build bzip2 at MacOS.
It seems bzip2 currently migrated from [sourceware](https://sourceware.org/git/?p=bzip2.git;a=summary) to [gitlab](https://gitlab.com/bzip2/bzip2), and it using `CMake` instead of pure `Makefile`, so I refurbished `bzip2` build script.
Here is the result of GitHub workflow : [Result](https://github.com/j8xixo12/devenv/runs/4131291353?check_suite_focus=true#step:4:36254)
=> enhance: refurbished bzip2 build script

applications/solvcon/entry.sh
Since https://github.com/solvcon/devenv/pull/93 has landed to unblock the SOLVCON CI build of mac OS, the rest tasks should be merged to build SOLVCON by devenv[1].
[1] Verified by https://github.com/tai271828/solvcon/runs/4137753217?check_suite_focus=true
=> Revive the SOLVCON application - regular maintenance

scripts/build.d/bzip2
For https://github.com/solvcon/devenv/issues/92#issuecomment-962703670, changed the build script to use tarball by default, currently bzip2 latest release still using makefile and the issue of clang build fail still exist, so I choice the master as default tarball version, and I tried to download .tar.gz, .tar and .zip, the there are unable to untar except .zip, so I choice zip file to download.
Maybe we can waiting for the next release, the change the default version to latest release.
=> feat: bzip2 build script default using tarball

.github/workflows/build_pkg_runner.yml
When working on https://github.com/solvcon/devenv/issues/98 , I realized this issue https://github.com/solvcon/devenv/issues/101 is a part of #98 . This pull request will create new CI job to monitor any future regression like #101 .
Please note currently the build with git branch source on macOS will fail. This is expected because of #101 .
=> Create CI jobs to monitor the build process of scotch

.github/workflows/solvcon_runner.yml, contrib/ci-setup-apt.sh, contrib/ci-setup-ssh.sh, contrib/ci-show-dep.sh, contrib/ci-show-python-env.sh, contrib/ci-solvcon-function-test.sh
By using this environment variable, we add a compatibility layer to make
the helper scripts more general so they can be used in different
GITHUB_WORKSPACE.
Please note the trick of GITHUB_ENV. It is a CVE alternative. See
document of Github like:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Issue: #99
=> ci(SOLVCON): introduce DEVENV_WORKSPACE

scripts/build.d/numpy
I have not tested any Fortran compiler (gcc) binary for Apple Silicon.  At the moment I would like to allow building Numpy without Fortran.
=> Add a switch (env var) NOFORTRAN to not use fortran compiler for building numpy

scripts/build.d/scotch
Succeeding implementation for issue https://github.com/solvcon/devenv/issues/101#issuecomment-1039934241
Tested with https://github.com/tai271828/devenv/runs/5224295939?check_suite_focus=true
=> When building scotch with git, use the same version as the tarball in CI

scripts/build.d/cython
The latest numpy requires Cython 2.29.30
=> Upgrade Cython to 0.29.30 (from 0.29.24)

.github/workflows/build_pkg_runner.yml, scripts/build.d/hdf
It seems the naming convention of hdf5 upstream repository changed. Update the naming convention to revive the build.
=> Fix hdf5 build

scripts/build.d/libevent, scripts/build.d/tmux
tmux needs libevent, whose build script is added too.
Tested with RHEL 7.3.
This solves #120
=> Add build script for tmux

scripts/build.d/openssl, scripts/build.d/python, scripts/func.d/build_utils
* Upgrade and fix the Python build script to version 3.11.1.  Make pulling from git opt-in.
* Fix the openssl version by default.  Make pulling from git opt-in.
* Add an optional CURLARGS environment for adding "-k" to override bad certificate when downloading.
=> Update Python build script

scripts/build.d/cmake
CMake tarball download url is incorrectly composed. This hotfix corrects this problem.
=> fix: incorrectly composed cmake download url

scripts/cmd.d/packages
Add a command, `packages`, which will list all the packages supported by `devenv`.
These packages can be build with `devenv build`.
=> add command: list all support packages

scripts/env.d/devenv_impl
since egrep commnad has been deprecate, it should use `grep -E` instead. 
ref: https://www.phoronix.com/news/GNU-Grep-3.8-Stop-egrep-fgrep
=> fix: egrep is obsolescent

scripts/build.d/python, scripts/build.d/vim
I also found there's another `make test` in the build script of python, so I also modified it.
=> Add $BUILDTEST to determine whether to run 'make test' for vim & python build scripts

scripts/cmd.d/del
=> fix: display specific error message when deleting non-existing environment

scripts/build.d/automake, scripts/build.d/libxkbcommon, scripts/build.d/pkgconfig, scripts/build.d/xcb
To address the issue of outdated packages on NCHC's Taiwan-1, I have added some build scripts for the Qt dependencies.
One of the scripts is `XCB`, which includes several `XCB`-related packages within a single script. However, I am not entirely certain if this approach is appropriate. Thanks for reviewing my changes.
=> add qt deps' build script for NCHC machine

scripts/build.d/qt, var/patch/qt-6.5.0.patch
I've added changes to the Qt build script:
1. bump version to `6.5.0 LTS`
2. add configure options before build
3. replace `make` to `ninja-build`
4. skip extraction if the source code is already extracted
5. add a patch file to remove symlink check
=> Qt build script update

.github/workflows/shunit2_runner.yml
Since `macos-10-15` is outdated, therefore I have updated the macOS version of GitHub actions `Unittest - shunit2` from `macos-10-15` to `macos-latest`.
=> Update github actions macos version

applications/modmesh/twnia1_env.sh, scripts/build.d/libffi, scripts/build.d/pyside6, scripts/build.d/python, scripts/build.d/qt, scripts/build.d/xcb
This is a prototype for https://github.com/solvcon/devenv/issues/153. Here is what I've done:
Add new scripts:
1. `applications/modmesh/twnia1_env.sh`
- A PBS script that sets up the building environment for modmesh on a compute node.
- It takes around 1 hour to complete the job, which equals (1 * ncpus) CPU hours.
Most of the time is spent being blocked at `ar`(archiver) due to slow disk I/O, and the most economical number of ncpus has not yet been determined.
2. `scripts/build.d/libffi`
- Compute node lacks `libffi-devel`.
- Version `3.0.13` was decided to match the version of the login node.
- Official release from GitHub starts from [`3.3 RC0`](https://github.com/libffi/libffi/releases)
so I use a package url from `fedoraproject.org`.
Revise some scripts:
1. `scripts/build.d/python`: …
=> [add script] building modmesh env on twnia1

scripts/init, tests/runner.sh, tests/test_init.sh
In this PR I fix a `use` command issue which is the `use` command will use an unavailable flavor. 
After:
```
$ devenv use foo ; echo $DEVENVFLAVOR
flavor foo is not available
```
Before:
```
$ devenv use foo ; echo $DEVENVFLAVOR
flavor foo is not available
now using 'foo'
foo
```
=> Fix use flavor cmd

scripts/build.d/pybind11, scripts/build.d/qt
1. Advance Qt version to 6.6.3 to match with the github workflow.
2. Advance pybind11 version to 2.12.0 to meet minimum requirement of modmesh.
=> Advance pybind version to 2.12.0 and qt version to 6.6.3

scripts/build.d/qt
According to issue #166 , I comment the line 76 in `qt.d` and fix the bug of script.
https://github.com/solvcon/devenv/blob/ada270f51856644ea937581072eb8a43e5c54c84/scripts/build.d/qt#L76
=> fix bug in qt.d

.github/workflows/shunit2_runner.yml, scripts/build.d/qt
This PR is to address issue #171 . The Qt version in the build script is upgraded to 6.8.1 in alignment with GitHub workflow in modmesh.
=> upgrade Qt to 6.8.1 to sync with github workflow

scripts/build.d/qt
This PR updates the default Qt version in the build script to 6.6.3. Specifically, line 44 of the file scripts/build.d/qt was modified from: `pkgbranch=${VERSION:-6.5.3}` to `pkgbranch=${VERSION:-6.6.3}`. 
Please note that while this change updates the version reference, further testing for potential side effects of this update has not yet been conducted. I will perform testing once my new SSD arrives next week, as my current system is out of storage for building a virtual machine.
Related to #169
=> Align Qt version

scripts/build.d/cython, scripts/build.d/matplotlib, scripts/build.d/pybind11, scripts/build.d/pyside6, scripts/build.d/python, scripts/build.d/qt, scripts/build.d/scipy, scripts/build.d/zlib, scripts/func.d/build_utils
* Cython version bumps from 0.29.32 to 3.0.12
* matplotlib adds WIP build script
* numpy version bumps from 1.24.1 to 2.2.4
* pybind11 version bumps from 2.12.0 to 2.13.6
* PySide6 version bumps (and fix) to v.6.8.1
* Python version bumps from 3.11.6 to 3.13.2
* Qt fixes archived hash
* SciPy adds build script
* zlib version bumps from 1.2.13 to 1.3.1
* Add DEVENV_DLONLY env variable for the updated build scripts
* print more hash messages in the download_md5() shell function
=> Update build scripts for Python 3.13

scripts/build.d/cmake
Unable to build CMake ver. 3.28.1, as multiple errors occurred during the build process.
The error messages:
```bash
/Library/Developer/CommandLineTools/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
|          ^
/Users/tingweilin/devenv/flavors/prime/src/cmake-3.28.1/Utilities/cmzlib/zutil.h:147:33: note: expanded from macro 'fdopen'
147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
|                                 ^
/Library/Developer/CommandLineTools/usr/lib/clang/17/include/__stddef_null.h:26:16: note: expanded from macro 'NULL'
26 | #define NULL ((void*)0)
|                ^
In file included from …
```
=> Fix: Switch CMake version to 4.0.1

scripts/init
The current scripts/init script fails when tried in zsh because BASH_SOURCE[0] is empty in zsh, causing the DEVENVROOT path detection to fail.
```
scripts/init:.:3: no such file or directory: /Users/username/scripts/env.d/vars
```
```
+scripts/init:1> dirname ''           # BASH_SOURCE[0] is empty in zsh
+scripts/init:1> cd ./..              # Goes to parent of current dir, not script dir  
+scripts/init:1> export DEVENVROOT=/Users/username  # Wrong path!
```
- Enables devenv usage for zsh users (common on macOS)
```
source scripts/init
echo "DEVENVROOT: $DEVENVROOT"
devenv
bash -c "cd ~/devenv && source scripts/init && echo 'DEVENVROOT: $DEVENVROOT'"
```
[x] Tested on macOS with zsh 5.x
[x] Tested backward compatibility with bash
[x] Verified devenv functionality works after change its …
=> feat: Fix zsh compatibility in init script

.github/workflows/build_pkg_runner.yml, .github/workflows/shunit2_runner.yml, .github/workflows/solvcon_runner.yml
This PR fixes issue #175 by upgrading the deprecated Ubuntu CI runner version.
- Updated all GitHub Actions workflows to use ubuntu-22.04 instead of deprecated ubuntu-20.04
- Upgraded actions/checkout from v2 to v4 for better security and features
- .github/workflows/build_pkg_runner.yml
- .github/workflows/shunit2_runner.yml  
- .github/workflows/solvcon_runner.yml
The current runner version uses Ubuntu 20.04 which has been deprecated by GitHub Actions and causes CI jobs to fail. Ubuntu 22.04 is the current LTS version and is fully supported by GitHub Actions.
Fixes #175
=> Upgrade Ubuntu CI runner from ubuntu-20.04 to ubuntu-22.04
